name: Deploy to Remote

on: workflow_dispatch

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v3
            -   name: Set up JDK 17
                uses: actions/setup-java@v3
                with:
                    java-version: '17'
                    cache: 'gradle'
                    distribution: 'adopt'
            -   name: Set up server
                run: ./gradlew -PskipBuild=zombies-mapeditor :phantazm-server:setupServer
            -   name: Build & copy jar
                run: ./gradlew -PskipBuild=zombies-mapeditor :phantazm-server:copyJar
            -   name: Zip server files
                run: |
                    cd ./run/server-1
                    tar -czf /tmp/server.tar.gz server.jar libs
            -   name: Upload a Build Artifact
                uses: actions/upload-artifact@v3.1.2
                with:
                    name: build
                    path: /tmp/server.tar.gz                   
            -   name: Set up SSH
                run: |
                    mkdir -p ~/.ssh/
                    echo "$SSH_KEY" > ~/.ssh/deploy
                    chmod 600 ~/.ssh/deploy
                    cat >> ~/.ssh/config <<END
                    Host phantazm
                      HostName $SSH_HOST
                      User $SSH_USER
                      IdentityFile ~/.ssh/deploy
                      StrictHostKeyChecking no
                    END
                env:
                    SSH_KEY: ${{ secrets.SSH_KEY }}
                    SSH_HOST: ${{ secrets.SSH_HOST }}
                    SSH_USER: ${{ secrets.SSH_USER }}
